# Generated by Django 5.2.4 on 2025-07-27 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='publish_on',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
