# Generated by Django 5.2.4 on 2025-07-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_course_publish_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='publish_on',
            field=models.DateTimeField(),
        ),
    ]
