"""
Django settings for school project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&3oe=tb(9hnn3&$w_74!s1j93t#ev*j2m*9&5sv5gr-)j67f*h'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False # Production
DEBUG = True # Development

ALLOWED_HOSTS = ['*'] # localhost - 192.168.4.18 - www.school.com


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'core', # app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'school.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'school.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    ############ SQLITE ##############
    'default': {
        'ENGINE': 'django.db.backends.sqlite3', # mysql - #sqlserve - #oracle - postgresql
        'NAME': BASE_DIR / 'db.sqlite3',
    }
    ############ MySql ##############
    # pip install pymysql
    #import pymysql
    # pymysql.install_as_MySQLdb()
    # 'default' : {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'school',
    #     'USER' : 'root',
    #     'PASSWORD' : '1234',
    #     'HOST' : '127.0.0.1', # localhost 
    #     'PORT' : '3306'
    # }
    ############ Postgresql ##############
    # pip install psycopg2
    # 'default' : {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'school',
    #     'USER' : 'postgres',
    #     'PASSWORD' : '123',
    #     'HOST' : 'localhost', # localhost 
    #     'PORT' : '5432'
    # }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True # ar / en

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
